# Generated by Django 4.2 on 2025-05-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_cartitem_session_key_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='icon',
            field=models.CharField(choices=[('home', 'บ้าน'), ('office', 'ที่ทำงาน'), ('dorm', 'หอพัก')], default='home', max_length=20, verbose_name='ไอคอน'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='ชื่อที่อยู่'),
        ),
    ]
