# Generated by Django 4.2 on 2025-05-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_deliveryaddress_icon_deliveryaddress_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='icon',
            field=models.CharField(choices=[('home', 'บ้าน'), ('office', 'ที่ทำงาน'), ('other', 'อื่นๆ')], default='home', max_length=20, verbose_name='ไอคอน'),
        ),
    ]
