# Generated by Django 4.2 on 2025-05-13 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_alter_deliveryaddress_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
