# Generated by Django 4.2 on 2025-05-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_order_delivery_address_order_payment_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='slips/'),
        ),
    ]
