# Generated by Django 4.2 on 2025-05-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_order_slip_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='slip_image',
            new_name='payment_slip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอยืนยันชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
    ]
