# Generated by Django 4.2 on 2025-05-19 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0014_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurpriseBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='surprise_boxes/')),
                ('allergens', models.ManyToManyField(blank=True, to='myapp.allergen')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.category')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.coupon')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_surprise_boxes', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.restaurant')),
            ],
        ),
    ]
