# Generated by Django 4.2 on 2025-05-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_surprisebox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurpriseBox',
        ),
    ]
