# Generated by Django 4.2 on 2025-05-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_public',
            field=models.BooleanField(default=True, help_text='หากติ๊ก ✅ จะเปิดให้ผู้ใช้เห็นและเลือกใช้ได้'),
        ),
    ]
