# Generated by Django 4.2 on 2025-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_coupon_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_surprise_box',
            field=models.BooleanField(default=False, verbose_name='เป็นกล่องสุ่ม'),
        ),
    ]
