# Generated by Django 4.2 on 2025-05-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_slip_image_order_payment_slip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอยืนยันชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('preparing', 'กำลังเตรียมอาหาร'), ('delivering', 'กำลังจัดส่ง'), ('completed', 'ส่งสำเร็จ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
    ]
