# Generated by Django 4.2 on 2025-05-12 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='address_line',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='district',
            field=models.CharField(default='', max_length=100, verbose_name='เขต/อำเภอ'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='postal_code',
            field=models.CharField(default='', max_length=10, verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='province',
            field=models.CharField(default='', max_length=100, verbose_name='จังหวัด'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='street',
            field=models.CharField(default='', max_length=255, verbose_name='ที่อยู่/บ้านเลขที่'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='subdistrict',
            field=models.CharField(default='', max_length=100, verbose_name='แขวง/ตำบล'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='ที่อยู่หลัก'),
        ),
    ]
