# Generated by Django 4.2 on 2025-05-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_coupon_menuitem_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.deliveryaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('qr', 'PromptPay QR'), ('cod', 'ชำระเงินปลายทาง'), ('card', 'บัตรเครดิต')], default='cod', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'ยังไม่ชำระ'), ('paid', 'ชำระแล้ว')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
